### ISSUE TITLE
The final assembly in nuget does not have Strong Name

### ISSUE THREAD

**Issue by rmterra** [Turo-NET/UnicodeNormalization#1]

**Comment by R2D221** [comment]
I'm sorry, I'm new at this. What do you mean by Strong Name?

**Comment by rmterra** [comment]
Sorry for let you wait =x, the strong name is a digital signature of your assembly.

A signed assembly cannot reference another unsigned assembly, so anyone that want to download your nuget package cannot use it without re-sign before a deploy it

The process of signing is always made when you deploy your dll because it can harm the development process with some annoying validations

You can create and sign directly on Visual Studio or you can use some command line tools on Visual Studio Command prompt

That tools are "sn.exe" that creates a signature file and the 

You can create a signature using the "sn.exe" (Strong Name Tool) and sign your assemblies with "al.exe" (Assembly Linker)

More informations in:

https://msdn.microsoft.com/en-us/library/k5b5tt23(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/xc31ft41(v=vs.110).aspx

If I can help on more something can count on me =D

**Comment by R2D221** [comment]
It took me a while, but I finally uploaded a signed version (I hope it's working correctly)

You can get version 1.0.3 here (once it gets indexed, of course): https://www.nuget.org/packages/UnicodeNormalization/1.0.3
