### ISSUE TITLE
Newtonsoft 6.0 Error

### ISSUE THREAD

**Issue by gabrieligbastos** [Turo-NET/UnicodeNormalization#2]
Hi,

I was using this library and it was everything fine so far. Soon, I had to update my newtonsoft json from 6 to 7. I updated correctly all my packages, but I was getting an exception when using myString.Normalize();

Receiving this error:
System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Then, I cloned this solution, updated the json and it started to working. Some clue? Is it this package mistake or mine?

Thanks in regards,

**Comment by R2D221** [comment]
I'm pretty sure this must be a problem on my side. When I created this project, version 7 of Newtonsoft.Json wasn't released yet.

I will fix the dependencies and upload a new version.

**Comment by gabrieligbastos** [comment]
Hi,

Reading more about the issue, I found out, I could workaround this problem with BindingRedirect

This blog explain in details how everything works and the workaround.
http://blog.davidebbo.com/2011/01/nuget-versioning-part-1-taking-on-dll.html

You should read, maybe it is possible to avoid this problem in your side ;)

Thanks in regards for your help and attention, ;)

**Comment by R2D221** [comment]
I was busy with other projects all this time, but I finally fixed it. Now it uses Newtonsoft.Json 8.0.3.

It's already on NuGet: https://www.nuget.org/packages/UnicodeNormalization/1.0.3
