### ISSUE TITLE
UnicodeNormalization.UChar:generateUData () is too complex

### ISSUE THREAD

**Issue by ghost** [Turo-NET/UnicodeNormalization#3]
Hello,

I'm using this Nuget Package (V1.0.3) in a PCL with Xamarin.Forms application (Thanks for your work).

But on both Android and iOS application, when I call "text.Normalize(NormalizationForm.FormD)" there is an exception :
UnicodeNormalization.UChar:generateUData () is too complex

I roll back to the V1.0.1 version of the package, and no problem...

**Comment by R2D221** [comment]
Interesting. I changed how the normalization data is stored in memory,
thinking it would be better, but turns out it didn't work for Xamarin.

Thanks for the notice.

On Tue, Jun 28, 2016 at 7:12 AM, Jérôme Liger notifications@github.com
wrote:

> Hello,
> 
> I'm using this Nuget Package (V1.0.3) in a PCL with Xamarin.Forms
> application (Thanks for your work).
> 
> But on both Android and iOS application, when I call
> "text.Normalize(NormalizationForm.FormD)" there is an exception :
> UnicodeNormalization.UChar:generateUData () is too complex
> 
> I roll back to the V1.0.1 version of the package, and no problem...
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Turo-NET/UnicodeNormalization/issues/3, or mute the
> thread
> https://github.com/notifications/unsubscribe/AAvRr5WpldCr_9JjXOCDMSDc-I9Os-Dcks5qQQ-egaJpZM4JACKy
> .

## 

—Arturo Torres Sánchez

**Comment by R2D221** [comment]
Sorry it took so long. It's already fixed in version 1.0.4, along with Unicode 9.0.
